import { promises as fs } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { Client, Pool } from "pg";
import { Kysely, PostgresDialect } from "kysely";
import { runMigrator } from "./migrate.mts";

const UPDATE_SNAPSHOT = process.argv.includes("--update-snapshot");

const REPLAY_URL =
  process.env.DATABASE_URL_REPLAY ??
  "postgres://bookshelf:bookshelf@localhost:5432/bookshelf_replay";

const SNAPSHOT_PATH = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "../tests/fixtures/migration-schema-snapshot.json"
);

// Parse the replay URL to derive the admin URL (connect to "postgres" DB).
function adminUrl(replayUrl: string): { adminUrl: string; dbName: string } {
  const u = new URL(replayUrl);
  const dbName = u.pathname.slice(1); // strip leading "/"
  u.pathname = "/postgres";
  return { adminUrl: u.toString(), dbName };
}

async function dropAndCreateDb(): Promise<void> {
  const { adminUrl: url, dbName } = adminUrl(REPLAY_URL);
  const client = new Client({ connectionString: url });
  await client.connect();
  try {
    await client.query(
      `DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE)`
    );
    await client.query(`CREATE DATABASE "${dbName}"`);
  } finally {
    await client.end();
  }
}

interface ColumnInfo {
  name: string;
  type: string;
  nullable: boolean;
  default: string | null;
}

interface ConstraintInfo {
  name: string;
  type: string;
  definition: string;
}

interface IndexInfo {
  name: string;
  definition: string;
}

interface TableSnapshot {
  name: string;
  columns: ColumnInfo[];
  constraints: ConstraintInfo[];
  indexes: IndexInfo[];
}

interface SchemaSnapshot {
  tables: TableSnapshot[];
}

async function captureSnapshot(pool: Pool): Promise<SchemaSnapshot> {
  const client = await pool.connect();
  try {
    // Columns
    const colResult = await client.query<{
      table_name: string;
      column_name: string;
      data_type: string;
      is_nullable: string;
      column_default: string | null;
      ordinal_position: number;
    }>(`
      SELECT table_name, column_name, data_type, is_nullable, column_default, ordinal_position
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name NOT LIKE 'kysely_migration%'
      ORDER BY table_name, ordinal_position
    `);

    // Constraints
    const conResult = await client.query<{
      table_name: string;
      constraint_name: string;
      constraint_type: string;
    }>(`
      SELECT tc.table_name, tc.constraint_name, tc.constraint_type
      FROM information_schema.table_constraints tc
      WHERE tc.table_schema = 'public'
        AND tc.table_name NOT LIKE 'kysely_migration%'
      ORDER BY tc.table_name, tc.constraint_name
    `);

    // Indexes (excludes primary key and unique constraint indexes auto-generated by PG,
    // but includes explicitly created ones via pg_indexes)
    const idxResult = await client.query<{
      tablename: string;
      indexname: string;
      indexdef: string;
    }>(`
      SELECT tablename, indexname, indexdef
      FROM pg_indexes
      WHERE schemaname = 'public'
        AND tablename NOT LIKE 'kysely_migration%'
      ORDER BY tablename, indexname
    `);

    // Group by table
    const tableMap = new Map<
      string,
      { columns: ColumnInfo[]; constraints: ConstraintInfo[]; indexes: IndexInfo[] }
    >();

    for (const row of colResult.rows) {
      if (!tableMap.has(row.table_name)) {
        tableMap.set(row.table_name, { columns: [], constraints: [], indexes: [] });
      }
      tableMap.get(row.table_name)!.columns.push({
        name: row.column_name,
        type: row.data_type,
        nullable: row.is_nullable === "YES",
        default: row.column_default ?? null,
      });
    }

    for (const row of conResult.rows) {
      if (!tableMap.has(row.table_name)) {
        tableMap.set(row.table_name, { columns: [], constraints: [], indexes: [] });
      }
      tableMap.get(row.table_name)!.constraints.push({
        name: row.constraint_name,
        type: row.constraint_type,
        definition: row.constraint_name,
      });
    }

    for (const row of idxResult.rows) {
      if (!tableMap.has(row.tablename)) {
        tableMap.set(row.tablename, { columns: [], constraints: [], indexes: [] });
      }
      tableMap.get(row.tablename)!.indexes.push({
        name: row.indexname,
        definition: row.indexdef,
      });
    }

    const tables: TableSnapshot[] = Array.from(tableMap.entries())
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, data]) => ({
        name,
        columns: data.columns,
        constraints: data.constraints.sort((a, b) =>
          a.name.localeCompare(b.name)
        ),
        indexes: data.indexes.sort((a, b) => a.name.localeCompare(b.name)),
      }));

    return { tables };
  } finally {
    client.release();
  }
}

async function assertNoUserTables(pool: Pool): Promise<void> {
  const client = await pool.connect();
  try {
    const result = await client.query<{ table_name: string }>(`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_name NOT LIKE 'kysely_migration%'
    `);
    if (result.rows.length > 0) {
      const names = result.rows.map((r) => r.table_name).join(", ");
      throw new Error(
        `After full reset, unexpected tables remain: ${names}`
      );
    }
  } finally {
    client.release();
  }
}

function diffSnapshots(a: SchemaSnapshot, b: SchemaSnapshot): string {
  const aStr = JSON.stringify(a, null, 2).split("\n");
  const bStr = JSON.stringify(b, null, 2).split("\n");
  const lines: string[] = [];
  const maxLen = Math.max(aStr.length, bStr.length);
  for (let i = 0; i < maxLen; i++) {
    const la = aStr[i] ?? "";
    const lb = bStr[i] ?? "";
    if (la !== lb) {
      lines.push(`L${i + 1}  - ${la}`);
      lines.push(`L${i + 1}  + ${lb}`);
    }
  }
  return lines.join("\n");
}

async function main(): Promise<void> {
  console.log("==> Migration replay test");
  console.log(`    Replay DB: ${REPLAY_URL}`);
  console.log(`    Snapshot:  ${SNAPSHOT_PATH}`);
  console.log(`    Update snapshot: ${UPDATE_SNAPSHOT}`);
  console.log();

  // 1. Drop and recreate the replay DB
  console.log("[1/6] Drop and create replay DB...");
  await dropAndCreateDb();

  const pool = new Pool({ connectionString: REPLAY_URL });
  const db = new Kysely<Record<string, never>>({
    dialect: new PostgresDialect({ pool }),
  });

  try {
    // 2. Migrate forward to latest
    console.log("[2/6] Migrate to latest...");
    const fwdResult = await runMigrator(db, "latest");
    if (fwdResult.error) throw fwdResult.error;
    for (const r of fwdResult.results ?? []) {
      console.log(`  ${r.status === "Success" ? "✓" : "✗"} ${r.migrationName}`);
    }

    // 3. Capture snapshot A
    console.log("[3/6] Capture snapshot A...");
    const snapshotA = await captureSnapshot(pool);
    console.log(`  Tables: ${snapshotA.tables.map((t) => t.name).join(", ")}`);

    // 4. Reset (roll back all)
    console.log("[4/6] Reset (migrate down all)...");
    const resetResult = await runMigrator(db, "reset");
    if (resetResult.error) throw resetResult.error;

    // 5. Assert no user tables remain
    console.log("[5/6] Assert no user tables remain after reset...");
    await assertNoUserTables(pool);
    console.log("  OK — no user tables");

    // 6. Migrate forward again
    console.log("[6/6] Migrate to latest (second pass)...");
    const fwd2Result = await runMigrator(db, "latest");
    if (fwd2Result.error) throw fwd2Result.error;
    for (const r of fwd2Result.results ?? []) {
      console.log(`  ${r.status === "Success" ? "✓" : "✗"} ${r.migrationName}`);
    }

    // Capture snapshot B
    const snapshotB = await captureSnapshot(pool);

    // Assert A === B (idempotency)
    const aJson = JSON.stringify(snapshotA);
    const bJson = JSON.stringify(snapshotB);
    if (aJson !== bJson) {
      console.error("\n✗ Snapshot A != Snapshot B (migrations are not idempotent!)");
      console.error(diffSnapshots(snapshotA, snapshotB));
      process.exit(1);
    }
    console.log("\n✓ Snapshot A == Snapshot B (migrations are idempotent)");

    if (UPDATE_SNAPSHOT) {
      await fs.writeFile(SNAPSHOT_PATH, JSON.stringify(snapshotB, null, 2) + "\n");
      console.log(`✓ Snapshot written to ${SNAPSHOT_PATH}`);
    } else {
      // Diff B against committed snapshot
      let committed: SchemaSnapshot;
      try {
        const raw = await fs.readFile(SNAPSHOT_PATH, "utf-8");
        committed = JSON.parse(raw) as SchemaSnapshot;
      } catch {
        console.error(
          `✗ No committed snapshot found at ${SNAPSHOT_PATH}.\n` +
            `  Run: npm run test:migrate-replay -- --update-snapshot`
        );
        process.exit(1);
      }

      const committedJson = JSON.stringify(committed);
      if (bJson !== committedJson) {
        console.error("\n✗ Current schema differs from committed snapshot!");
        console.error("  Run with --update-snapshot if the migration change is intentional.");
        console.error("\nDiff (current vs committed):");
        console.error(diffSnapshots(snapshotB, committed));
        process.exit(1);
      }
      console.log("✓ Schema matches committed snapshot");
    }

    console.log("\n✓ Migration replay test passed");
  } finally {
    await db.destroy();
  }
}

main().catch((err) => {
  console.error("Migration replay test FAILED:", err);
  process.exit(1);
});
